### ISSUE TITLE
Add `Onyx::SQL.transaction` method

### ISSUE THREAD

**Issue by vladfaust** [onyxframework/onyx#14]
```crystal
Onyx::SQL.transaction do |tx|
  Onyx::SQL.exec(foo) # Repo uses transaction connection
  tx.commit
end
```

Should expand to:

```crystal
Onyx.db.transaction do |tx|
  Onyx::SQL.repo.db = tx.connection
  yield(tx)
  Onyx::SQL.repo.db = Onyx.db
end
```

Edit: updated with #16 proposals.

**Comment by aemadrid** [comment]
I'd say go one step further and auto-commit. We might need to add a way to cancel the transaction though:

```crystal
Onyx::SQL.transaction do |tx|
  res = Onyx::SQL.exec(foo) # Repo uses transaction connection
  tx.cancel if res.something?
end
```

**Comment by vladfaust** [comment]
@aemadrid, makes sense. We could then check if tx is closed with [`closed?`](http://crystal-lang.github.io/crystal-db/api/0.5.1/DB/Disposable.html#closed%3F-instance-method) method and commit it if it's not closed yet.
